# -*- coding: utf-8 -*-
"""Python_Week1_Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqYPTIEJW7Y7V0e1E7e5HzEpzx9lEV72
"""

# Python course for beginners
# Week 1
# assignment by Maya Betzalel

#### IMPORT PANDAS ####

import pandas as pd

#### CREATE DF ####
#1. dictionaries list:

data = {
    "subject_id": list(range(1, 7)),
    "gender": ["f", "m", "f", "f", "m", "m"],
    "age": [25, 30, 27, 19, 24, 35],
    "depression": [1, 1, 0, 0, 1, 0]

}

#2. create df

df = pd.DataFrame(data)

#3. print and save

print(df)
df.to_csv("week1_df.csv", index=False)

!pip install reportlab

