# -*- coding: utf-8 -*-
"""Python_Week1_Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kqYPTIEJW7Y7V0e1E7e5HzEpzx9lEV72
"""

# Python course for beginners
# Week 1
# assignment by Maya Betzalel

#### IMPORT PANDAS ####

import pandas as pd

#### CREATE DF ####
#1. dictionaries list:

data = {
	"subject_id": list(range(1, 7)),
	n = len(subject_id)
	gender = np.random.choice(["f", "m"], size=n, replace=True)
	age = np.random.randint(18, 41, size=n)
	depression = np.random.binomial(1, p=0.3, size=n)
}

#2. create df

df = pd.DataFrame(data)

#3. print and save

print(df)
df.to_csv("week1_df.csv", index=False)

!pip install reportlab

